### ISSUE TITLE
Падает((

### ISSUE THREAD

**Issue by polinavenberg** [ShFsn/Maze-Walker-2#6]
На моменте Select position of start and finish points. При нажатии любой цифры падает 
```
1
Traceback (most recent call last):
  File "C:\pyassist\Maze-Walker-2\Maze Walker II.py", line 15, in <module>
    seq.call(kb_event)
  File "C:\pyassist\Maze-Walker-2\bin\Sequencer.py", line 46, in call
    self._call_page(self._points_pos_select, key)
  File "C:\pyassist\Maze-Walker-2\bin\Sequencer.py", line 64, in _call_page
    page.action(key, self._maze)
  File "C:\pyassist\Maze-Walker-2\bin\pages\PointsPosSelect.py", line 17, in action
    maze.set_mp_maze(maze.get_data())
  File "C:\pyassist\Maze-Walker-2\bin\Maze.py", line 97, in set_mp_maze
    self._connector.set_mp_maze(data)
  File "C:\pyassist\Maze-Walker-2\bin\Connector.py", line 106, in set_mp_maze
    with open('data/server_data', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/server_data'
```

**Comment by ShFsn** [comment]
Fixed
